/*
 * Copyright 2022 Sony Semiconductor Solutions Corp. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// automatically generated by the FlatBuffers compiler, do not modify

import { flatbuffers } from 'flatbuffers'
/**
 * @enum {number}
 */
export namespace SmartCamera{
export enum BoundingBox{
  NONE= 0,
  BoundingBox2d= 1
}};

/**
 * @constructor
 */
export namespace SmartCamera{
export class BoundingBox2d {
  bb: flatbuffers.ByteBuffer|null = null

  bb_pos:number = 0
  /**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns BoundingBox2d
 */
  __init (i:number, bb:flatbuffers.ByteBuffer):BoundingBox2d {
    this.bb_pos = i
    this.bb = bb
    return this
  };

  /**
 * @param flatbuffers.ByteBuffer bb
 * @param BoundingBox2d= obj
 * @returns BoundingBox2d
 */
  static getRootAsBoundingBox2d (bb:flatbuffers.ByteBuffer, obj?:BoundingBox2d):BoundingBox2d {
    return (obj || new BoundingBox2d()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  };

  /**
 * @returns number
 */
  left ():number {
    const offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0
  };

  /**
 * @returns number
 */
  top ():number {
    const offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0
  };

  /**
 * @returns number
 */
  right ():number {
    const offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0
  };

  /**
 * @returns number
 */
  bottom ():number {
    const offset = this.bb!.__offset(this.bb_pos, 10)
    return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0
  };

  /**
 * @param flatbuffers.Builder builder
 */
  static startBoundingBox2d (builder:flatbuffers.Builder) {
    builder.startObject(4)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param number left
 */
  static addLeft (builder:flatbuffers.Builder, left:number) {
    builder.addFieldInt32(0, left, 0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param number top
 */
  static addTop (builder:flatbuffers.Builder, top:number) {
    builder.addFieldInt32(1, top, 0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param number right
 */
  static addRight (builder:flatbuffers.Builder, right:number) {
    builder.addFieldInt32(2, right, 0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param number bottom
 */
  static addBottom (builder:flatbuffers.Builder, bottom:number) {
    builder.addFieldInt32(3, bottom, 0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
  static endBoundingBox2d (builder:flatbuffers.Builder):flatbuffers.Offset {
    const offset = builder.endObject()
    return offset
  };

  static createBoundingBox2d (builder:flatbuffers.Builder, left:number, top:number, right:number, bottom:number):flatbuffers.Offset {
    BoundingBox2d.startBoundingBox2d(builder)
    BoundingBox2d.addLeft(builder, left)
    BoundingBox2d.addTop(builder, top)
    BoundingBox2d.addRight(builder, right)
    BoundingBox2d.addBottom(builder, bottom)
    return BoundingBox2d.endBoundingBox2d(builder)
  }
}
}
/**
 * @constructor
 */
export namespace SmartCamera{
export class GeneralObject {
  bb: flatbuffers.ByteBuffer|null = null

  bb_pos:number = 0
  /**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GeneralObject
 */
  __init (i:number, bb:flatbuffers.ByteBuffer):GeneralObject {
    this.bb_pos = i
    this.bb = bb
    return this
  };

  /**
 * @param flatbuffers.ByteBuffer bb
 * @param GeneralObject= obj
 * @returns GeneralObject
 */
  static getRootAsGeneralObject (bb:flatbuffers.ByteBuffer, obj?:GeneralObject):GeneralObject {
    return (obj || new GeneralObject()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  };

  /**
 * @returns number
 */
  classId ():number {
    const offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0
  };

  /**
 * @returns SmartCamera.BoundingBox
 */
  boundingBoxType ():SmartCamera.BoundingBox {
    const offset = this.bb!.__offset(this.bb_pos, 6)
    return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : SmartCamera.BoundingBox.NONE
  };

  /**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
  boundingBox<T extends flatbuffers.Table> (obj:T):T|null {
    const offset = this.bb!.__offset(this.bb_pos, 8)
    return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null
  };

  /**
 * @returns number
 */
  score ():number {
    const offset = this.bb!.__offset(this.bb_pos, 10)
    return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0
  };

  /**
 * @param flatbuffers.Builder builder
 */
  static startGeneralObject (builder:flatbuffers.Builder) {
    builder.startObject(4)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param number classId
 */
  static addClassId (builder:flatbuffers.Builder, classId:number) {
    builder.addFieldInt32(0, classId, 0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param SmartCamera.BoundingBox boundingBoxType
 */
  static addBoundingBoxType (builder:flatbuffers.Builder, boundingBoxType:SmartCamera.BoundingBox) {
    builder.addFieldInt8(1, boundingBoxType, SmartCamera.BoundingBox.NONE)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset boundingBoxOffset
 */
  static addBoundingBox (builder:flatbuffers.Builder, boundingBoxOffset:flatbuffers.Offset) {
    builder.addFieldOffset(2, boundingBoxOffset, 0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param number score
 */
  static addScore (builder:flatbuffers.Builder, score:number) {
    builder.addFieldFloat32(3, score, 0.0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
  static endGeneralObject (builder:flatbuffers.Builder):flatbuffers.Offset {
    const offset = builder.endObject()
    return offset
  };

  static createGeneralObject (builder:flatbuffers.Builder, classId:number, boundingBoxType:SmartCamera.BoundingBox, boundingBoxOffset:flatbuffers.Offset, score:number):flatbuffers.Offset {
    GeneralObject.startGeneralObject(builder)
    GeneralObject.addClassId(builder, classId)
    GeneralObject.addBoundingBoxType(builder, boundingBoxType)
    GeneralObject.addBoundingBox(builder, boundingBoxOffset)
    GeneralObject.addScore(builder, score)
    return GeneralObject.endGeneralObject(builder)
  }
}
}
/**
 * @constructor
 */
export namespace SmartCamera{
export class ObjectDetectionData {
  bb: flatbuffers.ByteBuffer|null = null

  bb_pos:number = 0
  /**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ObjectDetectionData
 */
  __init (i:number, bb:flatbuffers.ByteBuffer):ObjectDetectionData {
    this.bb_pos = i
    this.bb = bb
    return this
  };

  /**
 * @param flatbuffers.ByteBuffer bb
 * @param ObjectDetectionData= obj
 * @returns ObjectDetectionData
 */
  static getRootAsObjectDetectionData (bb:flatbuffers.ByteBuffer, obj?:ObjectDetectionData):ObjectDetectionData {
    return (obj || new ObjectDetectionData()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  };

  /**
 * @param number index
 * @param SmartCamera.GeneralObject= obj
 * @returns SmartCamera.GeneralObject
 */
  objectDetectionList (index: number, obj?:SmartCamera.GeneralObject):SmartCamera.GeneralObject|null {
    const offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? (obj || new SmartCamera.GeneralObject()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null
  };

  /**
 * @returns number
 */
  objectDetectionListLength ():number {
    const offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0
  };

  /**
 * @param flatbuffers.Builder builder
 */
  static startObjectDetectionData (builder:flatbuffers.Builder) {
    builder.startObject(1)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset objectDetectionListOffset
 */
  static addObjectDetectionList (builder:flatbuffers.Builder, objectDetectionListOffset:flatbuffers.Offset) {
    builder.addFieldOffset(0, objectDetectionListOffset, 0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
  static createObjectDetectionListVector (builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
    builder.startVector(4, data.length, 4)
    for (let i = data.length - 1; i >= 0; i--) {
      builder.addOffset(data[i])
    }
    return builder.endVector()
  };

  /**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
  static startObjectDetectionListVector (builder:flatbuffers.Builder, numElems:number) {
    builder.startVector(4, numElems, 4)
  };

  /**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
  static endObjectDetectionData (builder:flatbuffers.Builder):flatbuffers.Offset {
    const offset = builder.endObject()
    return offset
  };

  static createObjectDetectionData (builder:flatbuffers.Builder, objectDetectionListOffset:flatbuffers.Offset):flatbuffers.Offset {
    ObjectDetectionData.startObjectDetectionData(builder)
    ObjectDetectionData.addObjectDetectionList(builder, objectDetectionListOffset)
    return ObjectDetectionData.endObjectDetectionData(builder)
  }
}
}
/**
 * @constructor
 */
export namespace SmartCamera{
export class ObjectDetectionTop {
  bb: flatbuffers.ByteBuffer|null = null

  bb_pos:number = 0
  /**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ObjectDetectionTop
 */
  __init (i:number, bb:flatbuffers.ByteBuffer):ObjectDetectionTop {
    this.bb_pos = i
    this.bb = bb
    return this
  };

  /**
 * @param flatbuffers.ByteBuffer bb
 * @param ObjectDetectionTop= obj
 * @returns ObjectDetectionTop
 */
  static getRootAsObjectDetectionTop (bb:flatbuffers.ByteBuffer, obj?:ObjectDetectionTop):ObjectDetectionTop {
    return (obj || new ObjectDetectionTop()).__init(bb.readInt32(bb.position()) + bb.position(), bb)
  };

  /**
 * @param SmartCamera.ObjectDetectionData= obj
 * @returns SmartCamera.ObjectDetectionData|null
 */
  perception (obj?:SmartCamera.ObjectDetectionData):SmartCamera.ObjectDetectionData|null {
    const offset = this.bb!.__offset(this.bb_pos, 4)
    return offset ? (obj || new SmartCamera.ObjectDetectionData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null
  };

  /**
 * @param flatbuffers.Builder builder
 */
  static startObjectDetectionTop (builder:flatbuffers.Builder) {
    builder.startObject(1)
  };

  /**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset perceptionOffset
 */
  static addPerception (builder:flatbuffers.Builder, perceptionOffset:flatbuffers.Offset) {
    builder.addFieldOffset(0, perceptionOffset, 0)
  };

  /**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
  static endObjectDetectionTop (builder:flatbuffers.Builder):flatbuffers.Offset {
    const offset = builder.endObject()
    return offset
  };

  /**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
  static finishObjectDetectionTopBuffer (builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
    builder.finish(offset)
  };

  static createObjectDetectionTop (builder:flatbuffers.Builder, perceptionOffset:flatbuffers.Offset):flatbuffers.Offset {
    ObjectDetectionTop.startObjectDetectionTop(builder)
    ObjectDetectionTop.addPerception(builder, perceptionOffset)
    return ObjectDetectionTop.endObjectDetectionTop(builder)
  }
}
}
